Задание 1

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [ ]:
import numpy as np

In [ ]:
N=int(input())
x=np.arange(N-1, -1, -1)
print(x)

In [ ]:

n=int(input())
print('Результат: {}'.format(np.arange(n-1, -1,-1)))

10
Результат: [9 8 7 6 5 4 3 2 1 0]


Задание 2

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [ ]:
N=int(input())
mat=np.diag(np.arange(N-1, -1, -1)) 
print(mat)

6
[[5 0 0 0 0 0]
 [0 4 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 2 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 0]]


In [ ]:
n=int(input())
matrix=np.diag(np.arange(n,0,-1))
print('Итог: {}'.format(sum(sum(matrix))))

6
Итог: 21


Задание 3

Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [ ]:
from numpy import linalg

In [ ]:
a=np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b=np.array([4, 12, -3])
linalg.solve(a, b)

In [ ]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

Задание 4

Задание и входные данные к нему находятся в материалах занятия (ноутбук Python_9_Numpy.ipynb, раздел “Задача 4 домашнего задания”)

In [ ]:
from IPython.display import Image
Image("user_matrix.JPG")

In [ ]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [ ]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [ ]:
muls = np.apply_along_axis(cosine, 1, users_stats, next_user_stats)